# setup-app.yml

---
  - hosts: webservers
    become: true
    tasks:
      - name: Upload application file
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755
      
      - name: Create Simple Info Page
        copy:
          dest: /var/www/html/info.php
          content: "<h1> Info about our Web Server {{ ansible_hostname }} </h1>"

      - name: Configgure php.ini file
        lineinfile:
          path: /etc/php.ini
          regexp: ^short_open_tag
          line: 'short_open_tag=On'
        notify: restart apache


    handlers:
        - name: restart apache
          service: name=httpd state=restarted